{
 "title": "paymentservice",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "2020-05-14T10:38:53.906Z", "to": "2020-05-14T10:58:53.906Z" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances",
    "label": "instances",
    "query": "label_values(http_requests_received_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Percentage of Payment Requests served under 32ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_bucket{uri=\"/payments\",le=\"0.033554431\"} [$interval]))/sum(rate(http_server_requests_seconds_count{uri=\"/payments\"}[$interval])) * 100",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "Request duration within which 95% of Payment requests served",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[$__interval])) by (le))",
     "legendFormat": "Avg. Request Duration"
    }
   ]
  },
  {
   "title": "Percentage of CheckBankDetails API Calls under 16 msecs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_request_duration_milliseconds_bucket{uri=\"/checkDetails\",le=\"16\"}[1m])) / sum(rate(api_request_duration_milliseconds_count{uri=\"/checkDetails\"}[1m])) * 100",
     "legendFormat": "Percentage"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])"
    }
   ]
  },
  {
   "title": "jvm garbage collection memory consumed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_gc_live_data_size_bytes" }
   ]
  },
  {
   "title": "Requests currently in progress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Start time of the process",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{instance =~ \"$instances\"} * 1000"
    }
   ]
  },
  {
   "title": "jvm live threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "The duration of HTTP requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_bucket[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of open handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_handles", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Process working set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}