# Use config map for not-secret configuration data

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fraudservice.fullname" . }}-configmap

data:
  {{- toYaml .Values.config | nindent 2 }}