apiVersion: v1
kind: Service
metadata:
  name: {{ include "fraudservice.fullname" . }}-clusterip

  labels:
    {{- include "fraudservice.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "fraudservice.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 32224