version: "3"

services:
  tracing:
    image: jaegertracing/all-in-one:1.22
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 14250:14250
    networks:
      - default


networks:
  default:
    name: ${NETWORK_NAME}
