create table if not exists users (
    id integer generated by default as identity,
    user_id varchar(100) not null,
    first_name varchar(100) not null,
    last_name varchar(100) not null,
    dob varchar(50) not null,
    tax_id varchar(100) not null,
    password varchar(100) not null,
    primary key (id)
);
