name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

env:
  # TODO: Change variable to your image's name.
  GITHUB_WORKFLOW: payment-service
  IMAGE_NAME: paymentservice

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: caching
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Dependency Check
        run: make dependencyCheck

      - name: SpotBugs Check
        run: make spotbugs

      - name: Run Trufflehog scan
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: "--regex --entropy=True --max_depth=5 --exclude_paths tools/trufflehog/trufflehog_exclude_patterns.txt"


      - name: Create Build Artifact
        run: make build

